export const metaRegistry = {
  "articles/boxing-gloves-size-guide": () => import("./articles/boxing-gloves-size-guide/meta"),
  "articles/how-to-choose-boxing-gloves": () => import("./articles/how-to-choose-boxing-gloves/meta"),
  "articles/how-to-clean-boxing-gloves": () => import("./articles/how-to-clean-boxing-gloves/meta"),
  "articles/how-to-wrap-your-hands-for-boxing": () => import("./articles/how-to-wrap-your-hands-for-boxing/meta"),
  "boxing/gear/best-hand-wraps-for-boxing": () => import("./boxing/gear/best-hand-wraps-for-boxing/meta"),
  "boxing/gear/what-gloves-do-pro-boxers-use": () => import("./boxing/gear/what-gloves-do-pro-boxers-use/meta"),
  "boxing/gloves/best-boxing-gloves-brands": () => import("./boxing/gloves/what-boxing-gloves-do-pro-boxers-use/meta"),
  "boxing/guides/how-long-do-boxing-gloves-last": () => import("./boxing/guides/how-long-do-boxing-gloves-last/meta"),
  "reviews/best-boxing-gloves-2025": () => import("./reviews/best-boxing-gloves-2025/meta"),
  "reviews/best-boxing-gloves-for-beginners-2025": () => import("./reviews/best-boxing-gloves-for-beginners-2025/meta"),
  "reviews/best-boxing-gloves-for-heavy-bag-2025": () => import("./reviews/best-boxing-gloves-for-heavy-bag-2025/meta"),
  "reviews/best-boxing-gloves-for-sparring-2026": () => import("./reviews/best-boxing-gloves-for-sparring-2026/meta"),
  "reviews/best-boxing-gloves-under-100": () => import("./reviews/best-boxing-gloves-under-100/meta"),
};
